import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/header";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header />
          {children}
          {modal}
          <div id="modal-root"></div>
        </Providers>
      </body>
    </html>
  );
}
